version: '3'

vars:
  DOCSDIR: docs
  BUILD_DIR:
    sh: npx get_pbv output.dir

tasks:
  # build tasks ------------------------------------------------------
  default:
    desc: "Generate HTML and run checks."
    aliases: [build]
    silent: true
    cmds:
      - task: antora
      - task: redirect_tense
      - task: pagefind
      - task: checks

  local:
    desc: "Generate, run checks, and serve HTML."
    silent: true
    cmds:
      - task: antora
      - task: redirect_tense
      - task: pagefind
      - task: checks
      - task: serve

  quick:
    desc: "Generate, skip checks, and serve HTML."
    cmds:
      - task: antora
      - task: redirect_tense
      - task: pagefind
      - task: serve

  antora:
    desc: "Generate HTML with Antora."
    silent: true
    cmds:
      - echo "Generating HTML..."
      - npx antora --stacktrace --fetch antora-playbook.yml

  pagefind:
    desc: "Generate search indexes with Pagefind."
    silent: true
    cmds:
      - echo "Generating search indexes..."
      - npx pagefind -s {{.BUILD_DIR}} --root-selector article.doc

  redirect_tense:
    desc: "Fixes the past tense in Antora-generated meta redirect files."
    silent: true
    cmds:
      - npx fix_redirect_tense

  # run validity checks ----------------------------------------------
  checks:
    desc: "Run validity checks on Asciidoc and HTML."
    silent: true
    cmds:
      - echo "Running validity checks..."
      - task: links
      - task: vale

  links:
    desc: "Test links in generated HTML with htmltest."
    silent: true
    cmds:
      - echo "Testing links in generated HTML..."
      - bin/htmltest -c htmltest.yml -s {{.BUILD_DIR}}

  vale:
    desc: "Test prose in generated HTML with Vale."
    silent: true
    cmds:
      - echo "Testing prose..."
      - bin/vale --config vale/vale.ini {{.BUILD_DIR}}

  # serve the HTML in the build folder -------------------------------
  serve:
    desc: "Preview the generated HTML."
    silent: true
    cmds:
      - echo "Starting web server..."
      - npx http-server {{.BUILD_DIR}} -r -c-1 -g

  # cleanup tasks ----------------------------------------------------
  cleanup:
    desc: Removes the build folder and temporary build files.
    cmds:
      - echo -n "Cleaning up..."
      - task: cleanup-unix
      - task: cleanup-windows
      - echo "OK"
    silent: true

  cleanup-unix:
    platforms: [darwin, amd64]
    internal: true
    silent: true
    cmds:
      - rm -rf $BUILD_DIR tmp

  cleanup-windows:
    platforms: [windows]
    internal: true
    silent: true
    cmds:
      - deltree $BUILD_DIR
      - deltree tmp